dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - mkdir build && cd build
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake -D ENABLE_COVERAGE=TRUE ..
  - make -j2
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5
